### ISSUE TITLE
Registering a sidebar that includes characters causes errors and can't be deleted

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-sidebars#10]
Registering a sidebar with characters as below causes the customizer to break and the sidebar cannot be deleted.  
Fórmula de Conteúdo   f%c3%b3rmula-de-conte%c3%bado   

We should try to sanitize similarly to how we did with AgentPress Listings.

**Comment by katyfb13** [comment]
FYI to whom it may concern, I don't seem to have the ability to edit labels, milestone, assignee :cold_sweat:

**Comment by nathanrice** [comment]
Now you do!

**Comment by katyfb13** [comment]
ahh, you rock @nathanrice :guitar:

**Comment by nathanrice** [comment]
357bc65

**Comment by dreamwhisper** [comment]
- Fórmula de Conteúdo results in fc3b3rmula-de-contec3bado now and does not break the customizer and the sidebar can be deleted.
- Spaces are replaced with a dash
- $ is removed
- ç is changed to c3a7

I broke it though with using `123456` and can't delete it - the ID ended up as 0.

```Notice: register_sidebar was called incorrectly. No id was set in the arguments array for the "123456" sidebar. Defaulting to "0". Manually set the id to "0" to silence this notice and keep existing sidebar content. Please see Debugging in WordPress for more information. (This message was added in version 4.2.0.) in /var/www/freshrevolution.org/wp-includes/functions.php on line 4136

Oops! You are trying to delete a sidebar that does not exist, or cannot be deleted```

**Comment by nathanrice** [comment]
6afb321

**Comment by dreamwhisper** [comment]
@nathanrice numbers are working now. However, symbols only do break it, including just $

` \\` or `$`

Notice: register_sidebar was called incorrectly. No id was set in the arguments array for the "\\" sidebar. Defaulting to "". Manually set the id to "" to silence this notice and keep existing sidebar content. Please see Debugging in WordPress for more information. (This message was added in version 4.2.0.) in /var/www/freshrevolution.org/wp-includes/functions.php on line 4136

> !@#$%^&*()`~

> Notice: register_sidebar was called incorrectly. No id was set in the arguments array for the "!@#$%^&*()`~" sidebar. Defaulting to "". Manually set the id to "" to silence this notice and keep existing sidebar content. Please see Debugging in WordPress for more information. (This message was added in version 4.2.0.) in /var/www/freshrevolution.org/wp-includes/functions.php on line 4136

Same with:
`<>?:"{}|_+`
`<foo val=“bar” />`

`Ω≈ç√∫˜µ≤≥÷` works - changes to cf89e28988c3a7e2889ae288abcb9cc2b5e289a4e289a5c3b7

I'm stoked that I can use `(╯°□°）╯︵ ┻━┻)` with no problems.

Reference: https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt

Blame @nickcernis for that lovely resource ;)

I didn't try everything, but a selection of them (including more than this, but cleared my database).

![genesis simple sidebars fresh wordpress](https://cloud.githubusercontent.com/assets/1271053/23560842/c81dad48-0009-11e7-827b-bc8571299508.png)

**Comment by nathanrice** [comment]
e5c3b52

Ok, I think I have everything accounted for now.

**Comment by dreamwhisper** [comment]
Looks good to me:
![genesis simple sidebars fresh wordpress 1](https://cloud.githubusercontent.com/assets/1271053/23565489/c8f4b34e-001b-11e7-88e6-2516f83cf602.png)

I created a bunch of `normal` ones as well.

If someone finds something else, they have to be trying to break it.

**Comment by dreamwhisper** [comment]
@NicktheGeek before I close this, is there any new process for getting things into RM? What do you want done so this doesn't get lost?

**Comment by NicktheGeek** [comment]
It will have to be manually moved to gitlab. probably best to open a new issue there for this with a link to this issue for details on the fix.
