### ISSUE TITLE
Can't create sidebar.

### ISSUE THREAD

**Issue by Tenkir** [copyblogger/genesis-simple-sidebars#12]
When I try to create a sidebar is get this error message: 

Are you sure you want to do this?

Please try again.

**Comment by nathanrice** [comment]
Looks like it's an issue of the nonce not being verified.

Try logging out and logging back in, then creating the sidebar again. If that doesn't work, post some screenshots of the screen you see right before you submit the form to create the sidebar, and the screen that shows the error.
