### ISSUE TITLE
PHP Notices for "Undefined index" (PHP ver 5.4.45 ) (Debug mode on)

### ISSUE THREAD

**Issue by Ali-RMD** [copyblogger/genesis-simple-sidebars#17]
**Parameters:**
PHP 5.4.45
WordPress 4.5
Genesis 2.2.7
Genesis Simple Sidebar plugin 2.0.2
WP Debug mode: ON

**Issue:**

When post is saved, and any of the primary sidebar or secondary sidebar field is missing from edit screen, Undefined index: notices are shown:

Notice: Undefined index: _ss_sidebar in /wp-content/plugins/genesis-simple-sidebars/includes/inpost.php on line 83

Notice: Undefined index: _ss_sidebar_alt in /wp-content/plugins/genesis-simple-sidebars/includes/inpost.php on line 84

Note: these notices further result in "Cannot modify header information"
"Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/genesis-simple-sidebars/includes/inpost.php:83) in /wp-admin/post.php on line 197

**Possible fix:**

In plugin's file at wp-content / plugins / genesis-simple-sidebars / includes / inpost.php, changing following code at line# 82, fixes this:

Form:

$_sidebars = array(
'_ss_sidebar'     => $_POST['_ss_sidebar'],
'_ss_sidebar_alt' => $_POST['_ss_sidebar_alt'],
);

To:

$_sidebars = array(
'_ss_sidebar'     => isset($_POST['_ss_sidebar']) ? $_POST['_ss_sidebar'] : '',
'_ss_sidebar_alt' => isset($_POST['_ss_sidebar_alt']) ? $_POST['_ss_sidebar_alt'] : '',
);

Thanks !

**Comment by Timonvdm** [comment]
Thanx! This fixed it for me, hope it will be available in the next update

**Comment by nathanrice** [comment]
Thanks for the code! Seems like it works perfect! I'll be pushing this update out very shortly.

**Comment by Ali-RMD** [comment]
Glad it works! :)
