### ISSUE TITLE
Remove print_r( get_post_meta( get_the_ID() ) );

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-sidebars#18]
@nathanrice I noticed this displaying in the metabox:

![sidebar-metabox](https://cloud.githubusercontent.com/assets/1271053/23556217/d2388e5c-fff9-11e6-8e6b-4ede97a18fc9.png)

Looks like from here and left over from debugging?
https://github.com/copyblogger/genesis-simple-sidebars/blob/febb5ede11f23fa1f27f7040d6c8e533f08bb2cf/includes/class-genesis-simple-sidebars-entry.php#L38

**Comment by nathanrice** [comment]
dffb99c
