### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-sidebars#20]
Translations are not working in the develop branch for me. To reproduce:

1. Switch language to 'Deutsch' at Settings → General.
2. Visit Genesis → Simple Sidebars.

- Expected: “Add New Sidebar” reads “Neue Sidebar hinzufügen”
- Observed: “Add New Sidebar” is in English.

Moving the load textdomain call outside the Genesis_Simple_Sidebars class before the call to init solves this for me:

~~~php
add_action( 'plugins_loaded', 'genesis_simple_sidebars_load_plugin_textdomain' );
function genesis_simple_sidebars_load_plugin_textdomain() {
	load_plugin_textdomain( 'genesis-simple-sidebars', false, basename( dirname( __FILE__ ) ) . '/languages/' );
}

add_action( 'plugins_loaded', array( Genesis_Simple_Sidebars(), 'init' ) );
~~~

**Comment by dreamwhisper** [comment]
Confirmed:

![translate](https://cloud.githubusercontent.com/assets/1271053/23631039/3593e8b4-028b-11e7-9908-ba9bc71734e5.png)

**Comment by nickcernis** [comment]
×2. This looks good to me.
