### ISSUE TITLE
2.1.0: Sidebars created with Woo Sidebars no longer override Simple Sidebars

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-sidebars#25]
As [reported here](https://wordpress.org/support/topic/v2-1-0-not-working-with-woosidebars/), 2.1.0 no longer allows Woo Sidebars to override Simple Sidebars.

## To reproduce
1. Install and activate Genesis Simple Sidebars and [Woo Sidebars](https://wordpress.org/plugins/woosidebars/).
2. Visit Genesis → Simple Sidebars and add a new sidebar.
3. Visit Appearance → Widget Areas, and add a new Woo sidebar, setting it to override your Simple Sidebar on the default Sample Page:
    <img width="1225" alt="edit_widget_area_ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/25006647/abe00c04-2055-11e7-8880-699221c8fea1.png">
4. Add a text widget to the Woo and Simple Sidebars widget areas at Appearance → Widgets that identifies them:    
    <img width="479" alt="widgets_ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/25006745/01c237f0-2056-11e7-9b17-055766336885.png">
    <img width="476" alt="widgets_ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/25006778/1b8cc538-2056-11e7-8273-5578274f4cff.png">
5. Set your Sample Page to use the your Simple Sidebar widget area in the Primary Sidebar.
    <img width="284" alt="edit_page_ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/25006807/39ad6874-2056-11e7-9d7e-8b2602f24e9f.png">

## Expected behaviour
Under GSS 2.0.4, the sample page displays the Woo Sidebar:

<img width="931" alt="sample_page" src="https://cloud.githubusercontent.com/assets/647669/25006830/5b6dc864-2056-11e7-81f5-2589e1ffe13b.png">

## Observed behaviour
Under GSS 2.1.0, the Woo Sidebar no longer overrides the GSS one:

<img width="953" alt="sample_page" src="https://cloud.githubusercontent.com/assets/647669/25006872/7c5f3954-2056-11e7-9491-7dcd08256d74.png">

Have not yet looked into the cause but will report back if I do.

**Comment by nickcernis** [comment]
Issue seems to be that Woo Sidebars also filters sidebars_widgets:

`add_filter( 'sidebars_widgets', array( $this, 'replace_sidebars' ) );`

If I change priority on our filter the Woo override trumps ours replacement again:

add_filter( 'sidebars_widgets', array( $this, 'sidebars_widgets_filter' ), 11 );

**Comment by nathanrice** [comment]
Maybe this is a dumb question, but why in the world would someone want to simultaneously use two plugins that aim to do the same thing?

**Comment by nickcernis** [comment]
@nathanrice I thought the same but didn't question it directly – we see site owners using eight different slider plugins all the time in support.

Woo's sidebar plugin has some extra conditional options to apply sidebars to terms, post types, and WooCommerce pages in bulk that some customers may have wanted to use without sacrificing their existing Simple Sidebars:

<img width="1077" alt="edit_widget_area_ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/25021928/e03d2d48-208b-11e7-8e82-72a9c47c2516.png">

<img width="1102" alt="edit_widget_area_ _wp_test_ _wordpress" src="https://cloud.githubusercontent.com/assets/647669/25021945/f5037e30-208b-11e7-84e3-542d984b5677.png">

Or perhaps someone inherited a project that used SS but were more familiar with Woo, so installed that too without migrating SS sidebars and deactivating it? I can ask in the forums if you're more curious.

Technically this is a regression because we've broken a behaviour that used to work (albeit by accident), but I don't expect to see many reports of this. Am happy to say, “we recommend using one sidebar plugin” if you'd prefer not to alter filter priority.

**Comment by nathanrice** [comment]
Well, my only concern is that at some point, one of the sidebar plugins has to take priority. Someone could just as easily say that they want Simple Sidebars to override Woo Sidebars. So I'm not sure who should have final say with things like this.

I'll have to look into the repercussions of changing the priority on that hook ... to see if anything else would be affected. But if it's all good to change, I'll leave it up to you to make a recommendation on whether we should actually change it.

**Comment by nickcernis** [comment]
Could we add a filter so that people who want to change the priority can do? That may be a worthwhile compromise if we can. (At the moment I don't think people have a way to unhook and rehook at a different priority, but if they did we could offer that as a solution.)

**Comment by nathanrice** [comment]
```php
remove_filter( 'sidebars_widgets', array( Genesis_Simple_Sidebars()->core, 'sidebars_widgets_filter' ) );
add_filter( 'sidebars_widgets', array( Genesis_Simple_Sidebars()->core, 'sidebars_widgets_filter' ), 11 );
```

Would this work?

**Comment by nickcernis** [comment]
That does work – thanks. I missed that $core exposed the object instance.

Seems like a good workaround to offer anyone affected by this. We probably don't need to change the priority unless we start to see many reports. Please feel free to close this if you're happy with that option too.
