### ISSUE TITLE
Cannot delete sidebar created in older version without ID

### ISSUE THREAD

**Issue by sethjohnson1** [copyblogger/genesis-simple-sidebars#27]
I inherited a new website... I noticed this error:

register_sidebar called incorrectly. No id was set in the arguments array for the "404" sidebar. 

If I try to delete it from the simple sidebar admin I receive this error:

"Oops! You are trying to delete a sidebar that does not exist, or cannot be deleted"

I am assuming it was created with Simple Sidebars if I am given the option to delete it from there?

Any help would be appreciated before I start digging through the database, where I assume this lives.

*Update*  Yikes and it doesn't look like editing the ss-settings values is going to be very straightforward

**Comment by nickcernis** [comment]
Sorry to hear about the error, Seth. It sounds like you have a Simple Sidebar with an empty ID, which was possible in an earlier version of the plugin.

If you're able to share the value of your ss-settings row here, I'd be happy to take a look. You can either give the '404' sidebar an ID so it can be deleted via the admin area, or remove it from the row directly.

**Comment by sethjohnson1** [comment]
Thanks for getting back to me, here are my ss-settings:

`a:14:{s:10:"blank-left";a:2:{s:4:"name";s:5:"blank";s:11:"description";s:24:"all blank to remove text";}s:8:"footer-1";a:2:{s:4:"name";s:8:"footer 1";s:11:"description";s:0:"";}s:8:"about-us";a:2:{s:4:"name";s:13:"about-us-menu";s:11:"description";s:0:"";}s:8:"newsroom";a:2:{s:4:"name";s:8:"newsroom";s:11:"description";s:0:"";}s:11:"right-visit";a:2:{s:4:"name";s:13:"Visit Sidebar";s:11:"description";s:42:"This is the Visit section primary sidebar.";}i:0;a:2:{s:4:"name";s:3:"404";s:11:"description";s:0:"";}s:14:"right-about-us";a:2:{s:4:"name";s:16:"About Us Sidebar";s:11:"description";s:45:"This is the About Us section primary sidebar.";}s:15:"primary-support";a:2:{s:4:"name";s:28:"Support Sidebar contact only";s:11:"description";s:44:"This is the Support section primary sidebar.";}s:16:"primary-research";a:2:{s:4:"name";s:16:"Research Sidebar";s:11:"description";s:45:"This is the Research section primary sidebar.";}s:13:"primary-learn";a:2:{s:4:"name";s:13:"Learn Sidebar";s:11:"description";s:42:"This is the Learn section primary sidebar.";}s:18:"landingpagesidebar";a:2:{s:4:"name";s:20:"Landing Page Sidebar";s:11:"description";s:0:"";}s:7:"whitney";a:2:{s:4:"name";s:7:"whitney";s:11:"description";s:0:"";}s:16:"mrl-digital-coll";a:2:{s:4:"name";s:23:"MRL Digital Collections";s:11:"description";s:27:"Custom left navigation menu";}s:22:"support-sidebar-amazon";a:2:{s:4:"name";s:22:"Support Sidebar-Amazon";s:11:"description";s:49:"Development membership contact info / AmazonSmile";}}`

I am not certain of the proper way to attach an ID to it, hoping you might know off the top of your head.

**Comment by sethjohnson1** [comment]
Sorry, that was much easier than I thought. I was able to assign an ID and then remove it. Thanks for getting back to me!
