### ISSUE TITLE
PHP errors with debug running PHP 5.4

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-sidebars#8]
Warning: Illegal string offset 'name' in wp-content/plugins/genesis-simple-sidebars/plugin.php on line 105

Warning: Illegal string offset 'description' in wp-content/plugins/genesis-simple-sidebars/plugin.php on line 107

Warning: Cannot modify header information - headers already sent by (output started at wp-content/plugins/genesis-simple-sidebars/plugin.php:105) in /public_html/wp-login.php on line 415

Warning: Cannot modify header information - headers already sent by (output started at wp-content/plugins/genesis-simple-sidebars/plugin.php:105) in /public_html/wp-login.php on line 427

**Comment by andrearennick** [comment]
Just as a follow up, since people think this is breaking from WP upgrades:

It happens when people have an empty sidebar saved in the db. They basically have to delete tables to fix it.

**Comment by dreamwhisper** [comment]
@nathanrice this is still coming up: https://wordpress.org/support/topic/php-warnings-after-update

**Comment by dreamwhisper** [comment]
Also noting, this is coming up in the logs quite a bit on Synthesis.

**Comment by nathanrice** [comment]
97fac5c
